//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSDigitalizar
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/service/", ConfigurationName="WSDigitalizar.IReceptor")]
    public interface IReceptor
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/RegistroDigitalizarDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSDigitalizar.RegistroDigitalizarDocumentoResponse1> RegistroDigitalizarDocumentoAsync(WSDigitalizar.RegistroDigitalizarDocumentoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ConsultaEDocumentDigitalizarDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSDigitalizar.ConsultaEDocumentDigitalizarDocumentoResponse> ConsultaEDocumentDigitalizarDocumentoAsync(WSDigitalizar.ConsultaEDocumentDigitalizarDocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ConsultaTipoDeDocumento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WSDigitalizar.ConsultaTipoDeDocumentoResponse1> ConsultaTipoDeDocumentoAsync(WSDigitalizar.ConsultaTipoDeDocumentoRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class RegistroDigitalizarDocumentoRequest
    {
        
        private string correoElectronicoField;
        
        private Documento documentoField;
        
        private PeticionBase peticionBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string correoElectronico
        {
            get
            {
                return this.correoElectronicoField;
            }
            set
            {
                this.correoElectronicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Documento documento
        {
            get
            {
                return this.documentoField;
            }
            set
            {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PeticionBase peticionBase
        {
            get
            {
                return this.peticionBaseField;
            }
            set
            {
                this.peticionBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class Documento
    {
        
        private int idTipoDocumentoField;
        
        private string nombreDocumentoField;
        
        private string rfcConsultaField;
        
        private byte[] archivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int idTipoDocumento
        {
            get
            {
                return this.idTipoDocumentoField;
            }
            set
            {
                this.idTipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string nombreDocumento
        {
            get
            {
                return this.nombreDocumentoField;
            }
            set
            {
                this.nombreDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string rfcConsulta
        {
            get
            {
                return this.rfcConsultaField;
            }
            set
            {
                this.rfcConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] archivo
        {
            get
            {
                return this.archivoField;
            }
            set
            {
                this.archivoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class TipoDeDocumento
    {
        
        private long idTipoDeDocumentoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long idTipoDeDocumento
        {
            get
            {
                return this.idTipoDeDocumentoField;
            }
            set
            {
                this.idTipoDeDocumentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class ConsultaTipoDeDocumentoResponse
    {
        
        private TipoDeDocumento[] tiposDeDocumentosField;
        
        private RespuestaBase respuestaBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tipoDeDocumento", IsNullable=false)]
        public TipoDeDocumento[] tiposDeDocumentos
        {
            get
            {
                return this.tiposDeDocumentosField;
            }
            set
            {
                this.tiposDeDocumentosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public RespuestaBase respuestaBase
        {
            get
            {
                return this.respuestaBaseField;
            }
            set
            {
                this.respuestaBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/common/ws/oxml/respuesta")]
    public partial class RespuestaBase
    {
        
        private bool tieneErrorField;
        
        private string[][] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool tieneError
        {
            get
            {
                return this.tieneErrorField;
            }
            set
            {
                this.tieneErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mensaje", typeof(string), IsNullable=false)]
        public string[][] error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class ConsultaTipoDeDocumentoRequest
    {
        
        private PeticionBase peticionBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PeticionBase peticionBase
        {
            get
            {
                return this.peticionBaseField;
            }
            set
            {
                this.peticionBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/common/ws/oxml/respuesta")]
    public partial class PeticionBase
    {
        
        private FirmaElectronica firmaElectronicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FirmaElectronica firmaElectronica
        {
            get
            {
                return this.firmaElectronicaField;
            }
            set
            {
                this.firmaElectronicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/common/ws/oxml/respuesta")]
    public partial class FirmaElectronica
    {
        
        private byte[] certificadoField;
        
        private string cadenaOriginalField;
        
        private byte[] firmaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] certificado
        {
            get
            {
                return this.certificadoField;
            }
            set
            {
                this.certificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cadenaOriginal
        {
            get
            {
                return this.cadenaOriginalField;
            }
            set
            {
                this.cadenaOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] firma
        {
            get
            {
                return this.firmaField;
            }
            set
            {
                this.firmaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class ConsultaDigitalizarDocumentoResponse
    {
        
        private string numeroDeTramiteField;
        
        private string eDocumentField;
        
        private string cadenaOriginalField;
        
        private RespuestaBase respuestaBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroDeTramite
        {
            get
            {
                return this.numeroDeTramiteField;
            }
            set
            {
                this.numeroDeTramiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string eDocument
        {
            get
            {
                return this.eDocumentField;
            }
            set
            {
                this.eDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string cadenaOriginal
        {
            get
            {
                return this.cadenaOriginalField;
            }
            set
            {
                this.cadenaOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public RespuestaBase respuestaBase
        {
            get
            {
                return this.respuestaBaseField;
            }
            set
            {
                this.respuestaBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class ConsultaDigitalizarDocumentoRequest
    {
        
        private long numeroOperacionField;
        
        private PeticionBase peticionBaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long numeroOperacion
        {
            get
            {
                return this.numeroOperacionField;
            }
            set
            {
                this.numeroOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PeticionBase peticionBase
        {
            get
            {
                return this.peticionBaseField;
            }
            set
            {
                this.peticionBaseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class AcuseDigitalizarDocumento
    {
        
        private RespuestaBase respuestaBaseField;
        
        private long numeroOperacionField;
        
        private System.DateTime horaRecepcionField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RespuestaBase respuestaBase
        {
            get
            {
                return this.respuestaBaseField;
            }
            set
            {
                this.respuestaBaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long numeroOperacion
        {
            get
            {
                return this.numeroOperacionField;
            }
            set
            {
                this.numeroOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime horaRecepcion
        {
            get
            {
                return this.horaRecepcionField;
            }
            set
            {
                this.horaRecepcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento")]
    public partial class RegistroDigitalizarDocumentoResponse
    {
        
        private RespuestaBase respuestaBaseField;
        
        private AcuseDigitalizarDocumento acuseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RespuestaBase respuestaBase
        {
            get
            {
                return this.respuestaBaseField;
            }
            set
            {
                this.respuestaBaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AcuseDigitalizarDocumento acuse
        {
            get
            {
                return this.acuseField;
            }
            set
            {
                this.acuseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroDigitalizarDocumentoRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento", Order=0)]
        public WSDigitalizar.RegistroDigitalizarDocumentoRequest registroDigitalizarDocumentoServiceRequest;
        
        public RegistroDigitalizarDocumentoRequest1()
        {
        }
        
        public RegistroDigitalizarDocumentoRequest1(WSDigitalizar.RegistroDigitalizarDocumentoRequest registroDigitalizarDocumentoServiceRequest)
        {
            this.registroDigitalizarDocumentoServiceRequest = registroDigitalizarDocumentoServiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroDigitalizarDocumentoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento", Order=0)]
        public WSDigitalizar.RegistroDigitalizarDocumentoResponse registroDigitalizarDocumentoServiceResponse;
        
        public RegistroDigitalizarDocumentoResponse1()
        {
        }
        
        public RegistroDigitalizarDocumentoResponse1(WSDigitalizar.RegistroDigitalizarDocumentoResponse registroDigitalizarDocumentoServiceResponse)
        {
            this.registroDigitalizarDocumentoServiceResponse = registroDigitalizarDocumentoServiceResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaEDocumentDigitalizarDocumentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento", Order=0)]
        public WSDigitalizar.ConsultaDigitalizarDocumentoRequest consultaDigitalizarDocumentoServiceRequest;
        
        public ConsultaEDocumentDigitalizarDocumentoRequest()
        {
        }
        
        public ConsultaEDocumentDigitalizarDocumentoRequest(WSDigitalizar.ConsultaDigitalizarDocumentoRequest consultaDigitalizarDocumentoServiceRequest)
        {
            this.consultaDigitalizarDocumentoServiceRequest = consultaDigitalizarDocumentoServiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaEDocumentDigitalizarDocumentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento", Order=0)]
        public WSDigitalizar.ConsultaDigitalizarDocumentoResponse consultaDigitalizarDocumentoServiceResponse;
        
        public ConsultaEDocumentDigitalizarDocumentoResponse()
        {
        }
        
        public ConsultaEDocumentDigitalizarDocumentoResponse(WSDigitalizar.ConsultaDigitalizarDocumentoResponse consultaDigitalizarDocumentoServiceResponse)
        {
            this.consultaDigitalizarDocumentoServiceResponse = consultaDigitalizarDocumentoServiceResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaTipoDeDocumentoRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WSDigitalizar.ConsultaTipoDeDocumentoRequest consultaTipoDocumentoServiceRequest;
        
        public ConsultaTipoDeDocumentoRequest1()
        {
        }
        
        public ConsultaTipoDeDocumentoRequest1(WSDigitalizar.ConsultaTipoDeDocumentoRequest consultaTipoDocumentoServiceRequest)
        {
            this.consultaTipoDocumentoServiceRequest = consultaTipoDocumentoServiceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaTipoDeDocumentoResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/aga/digitalizar/ws/oxml/DigitalizarDocumento", Order=0)]
        public WSDigitalizar.ConsultaTipoDeDocumentoResponse consultaTipoDocumentoServiceResponse;
        
        public ConsultaTipoDeDocumentoResponse1()
        {
        }
        
        public ConsultaTipoDeDocumentoResponse1(WSDigitalizar.ConsultaTipoDeDocumentoResponse consultaTipoDocumentoServiceResponse)
        {
            this.consultaTipoDocumentoServiceResponse = consultaTipoDocumentoServiceResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IReceptorChannel : WSDigitalizar.IReceptor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ReceptorClient : System.ServiceModel.ClientBase<WSDigitalizar.IReceptor>, WSDigitalizar.IReceptor
    {
        
        public ReceptorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSDigitalizar.RegistroDigitalizarDocumentoResponse1> WSDigitalizar.IReceptor.RegistroDigitalizarDocumentoAsync(WSDigitalizar.RegistroDigitalizarDocumentoRequest1 request)
        {
            return base.Channel.RegistroDigitalizarDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSDigitalizar.RegistroDigitalizarDocumentoResponse1> RegistroDigitalizarDocumentoAsync(WSDigitalizar.RegistroDigitalizarDocumentoRequest registroDigitalizarDocumentoServiceRequest)
        {
            WSDigitalizar.RegistroDigitalizarDocumentoRequest1 inValue = new WSDigitalizar.RegistroDigitalizarDocumentoRequest1();
            inValue.registroDigitalizarDocumentoServiceRequest = registroDigitalizarDocumentoServiceRequest;
            return ((WSDigitalizar.IReceptor)(this)).RegistroDigitalizarDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSDigitalizar.ConsultaEDocumentDigitalizarDocumentoResponse> WSDigitalizar.IReceptor.ConsultaEDocumentDigitalizarDocumentoAsync(WSDigitalizar.ConsultaEDocumentDigitalizarDocumentoRequest request)
        {
            return base.Channel.ConsultaEDocumentDigitalizarDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSDigitalizar.ConsultaEDocumentDigitalizarDocumentoResponse> ConsultaEDocumentDigitalizarDocumentoAsync(WSDigitalizar.ConsultaDigitalizarDocumentoRequest consultaDigitalizarDocumentoServiceRequest)
        {
            WSDigitalizar.ConsultaEDocumentDigitalizarDocumentoRequest inValue = new WSDigitalizar.ConsultaEDocumentDigitalizarDocumentoRequest();
            inValue.consultaDigitalizarDocumentoServiceRequest = consultaDigitalizarDocumentoServiceRequest;
            return ((WSDigitalizar.IReceptor)(this)).ConsultaEDocumentDigitalizarDocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSDigitalizar.ConsultaTipoDeDocumentoResponse1> WSDigitalizar.IReceptor.ConsultaTipoDeDocumentoAsync(WSDigitalizar.ConsultaTipoDeDocumentoRequest1 request)
        {
            return base.Channel.ConsultaTipoDeDocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSDigitalizar.ConsultaTipoDeDocumentoResponse1> ConsultaTipoDeDocumentoAsync(WSDigitalizar.ConsultaTipoDeDocumentoRequest consultaTipoDocumentoServiceRequest)
        {
            WSDigitalizar.ConsultaTipoDeDocumentoRequest1 inValue = new WSDigitalizar.ConsultaTipoDeDocumentoRequest1();
            inValue.consultaTipoDocumentoServiceRequest = consultaTipoDocumentoServiceRequest;
            return ((WSDigitalizar.IReceptor)(this)).ConsultaTipoDeDocumentoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
