//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsVentanillaUnica
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/service/", ConfigurationName="wsVentanillaUnica.IReceptor")]
    public interface IReceptor
    {




        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/RecibirCove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Persona))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComprobanteValorElectronicoBase))]
        System.Threading.Tasks.Task<wsVentanillaUnica.RecibirCoveResponse> RecibirCoveAsync(wsVentanillaUnica.RecibirCoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/RecibirRelacionFacturasIA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Persona))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComprobanteValorElectronicoBase))]
        System.Threading.Tasks.Task<wsVentanillaUnica.RecibirRelacionFacturasIAResponse> RecibirRelacionFacturasIAAsync(wsVentanillaUnica.RecibirRelacionFacturasIARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/RecibirRelacionFacturasNoIA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Persona))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ComprobanteValorElectronicoBase))]
        System.Threading.Tasks.Task<wsVentanillaUnica.RecibirRelacionFacturasNoIAResponse> RecibirRelacionFacturasNoIAAsync(wsVentanillaUnica.RecibirRelacionFacturasNoIARequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class ComprobanteValorElectronico : ComprobanteValorElectronicoBase
    {
        
        private string numeroFacturaOriginalField;
        
        private FacturaCove facturaField;
        
        private Emisor emisorField;
        
        private Destinatario destinatarioField;
        
        private Mercancia[] mercanciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroFacturaOriginal
        {
            get
            {
                return this.numeroFacturaOriginalField;
            }
            set
            {
                this.numeroFacturaOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FacturaCove factura
        {
            get
            {
                return this.facturaField;
            }
            set
            {
                this.facturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Emisor emisor
        {
            get
            {
                return this.emisorField;
            }
            set
            {
                this.emisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Destinatario destinatario
        {
            get
            {
                return this.destinatarioField;
            }
            set
            {
                this.destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mercancias", Order=4)]
        public Mercancia[] mercancias
        {
            get
            {
                return this.mercanciasField;
            }
            set
            {
                this.mercanciasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FacturaNoIA))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FacturaIA))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FacturaCove
    {
        
        private int certificadoOrigenField;
        
        private string numeroExportadorAutorizadoField;
        
        private int subdivisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int certificadoOrigen
        {
            get
            {
                return this.certificadoOrigenField;
            }
            set
            {
                this.certificadoOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string numeroExportadorAutorizado
        {
            get
            {
                return this.numeroExportadorAutorizadoField;
            }
            set
            {
                this.numeroExportadorAutorizadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int subdivision
        {
            get
            {
                return this.subdivisionField;
            }
            set
            {
                this.subdivisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Acuse
    {
        
        private string numeroDeOperacionField;
        
        private System.DateTime horaRecepcionField;
        
        private string mensajeInformativoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroDeOperacion
        {
            get
            {
                return this.numeroDeOperacionField;
            }
            set
            {
                this.numeroDeOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime horaRecepcion
        {
            get
            {
                return this.horaRecepcionField;
            }
            set
            {
                this.horaRecepcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mensajeInformativo
        {
            get
            {
                return this.mensajeInformativoField;
            }
            set
            {
                this.mensajeInformativoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Domicilio
    {
        
        private string calleField;
        
        private string numeroExteriorField;
        
        private string numeroInteriorField;
        
        private string coloniaField;
        
        private string localidadField;
        
        private string municipioField;
        
        private string entidadFederativaField;
        
        private string paisField;
        
        private string codigoPostalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string calle
        {
            get
            {
                return this.calleField;
            }
            set
            {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string numeroExterior
        {
            get
            {
                return this.numeroExteriorField;
            }
            set
            {
                this.numeroExteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string numeroInterior
        {
            get
            {
                return this.numeroInteriorField;
            }
            set
            {
                this.numeroInteriorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string colonia
        {
            get
            {
                return this.coloniaField;
            }
            set
            {
                this.coloniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string localidad
        {
            get
            {
                return this.localidadField;
            }
            set
            {
                this.localidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string municipio
        {
            get
            {
                return this.municipioField;
            }
            set
            {
                this.municipioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string entidadFederativa
        {
            get
            {
                return this.entidadFederativaField;
            }
            set
            {
                this.entidadFederativaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string pais
        {
            get
            {
                return this.paisField;
            }
            set
            {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string codigoPostal
        {
            get
            {
                return this.codigoPostalField;
            }
            set
            {
                this.codigoPostalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Emisor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Destinatario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public abstract partial class Persona
    {
        
        private int tipoIdentificadorField;
        
        private string identificacionField;
        
        private string apellidoPaternoField;
        
        private string apellidoMaternoField;
        
        private string nombreField;
        
        private Domicilio domicilioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int tipoIdentificador
        {
            get
            {
                return this.tipoIdentificadorField;
            }
            set
            {
                this.tipoIdentificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string identificacion
        {
            get
            {
                return this.identificacionField;
            }
            set
            {
                this.identificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string apellidoPaterno
        {
            get
            {
                return this.apellidoPaternoField;
            }
            set
            {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string apellidoMaterno
        {
            get
            {
                return this.apellidoMaternoField;
            }
            set
            {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public Domicilio domicilio
        {
            get
            {
                return this.domicilioField;
            }
            set
            {
                this.domicilioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Emisor : Persona
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Destinatario : Persona
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class DescripcionMercancia
    {
        
        private string marcaField;
        
        private string modeloField;
        
        private string subModeloField;
        
        private string numeroSerieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string marca
        {
            get
            {
                return this.marcaField;
            }
            set
            {
                this.marcaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string modelo
        {
            get
            {
                return this.modeloField;
            }
            set
            {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string subModelo
        {
            get
            {
                return this.subModeloField;
            }
            set
            {
                this.subModeloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string numeroSerie
        {
            get
            {
                return this.numeroSerieField;
            }
            set
            {
                this.numeroSerieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class Mercancia
    {
        
        private string descripcionGenericaField;
        
        private string claveUnidadMedidaField;
        
        private string tipoMonedaField;
        
        private decimal cantidadField;
        
        private decimal valorUnitarioField;
        
        private decimal valorTotalField;
        
        private decimal valorDolaresField;
        
        private DescripcionMercancia[] descripcionesEspecificasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string descripcionGenerica
        {
            get
            {
                return this.descripcionGenericaField;
            }
            set
            {
                this.descripcionGenericaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string claveUnidadMedida
        {
            get
            {
                return this.claveUnidadMedidaField;
            }
            set
            {
                this.claveUnidadMedidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tipoMoneda
        {
            get
            {
                return this.tipoMonedaField;
            }
            set
            {
                this.tipoMonedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal valorUnitario
        {
            get
            {
                return this.valorUnitarioField;
            }
            set
            {
                this.valorUnitarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal valorTotal
        {
            get
            {
                return this.valorTotalField;
            }
            set
            {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal valorDolares
        {
            get
            {
                return this.valorDolaresField;
            }
            set
            {
                this.valorDolaresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("descripcionesEspecificas", Order=7)]
        public DescripcionMercancia[] descripcionesEspecificas
        {
            get
            {
                return this.descripcionesEspecificasField;
            }
            set
            {
                this.descripcionesEspecificasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FirmaElectronica
    {
        
        private byte[] certificadoField;
        
        private string cadenaOriginalField;
        
        private byte[] firmaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] certificado
        {
            get
            {
                return this.certificadoField;
            }
            set
            {
                this.certificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cadenaOriginal
        {
            get
            {
                return this.cadenaOriginalField;
            }
            set
            {
                this.cadenaOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] firma
        {
            get
            {
                return this.firmaField;
            }
            set
            {
                this.firmaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComprobanteValorElectronicoNoIA))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComprobanteValorElectronicoIA))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ComprobanteValorElectronico))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public abstract partial class ComprobanteValorElectronicoBase
    {
        
        private string edocumentField;
        
        private TipoOperacion tipoOperacionField;
        
        private string[] patenteAduanalField;
        
        private System.DateTime fechaExpedicionField;
        
        private string observacionesField;
        
        private string[] rfcConsultaField;
        
        private int tipoFiguraField;
        
        private string correoElectronicoField;
        
        private FirmaElectronica firmaElectronicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("e-document", IsNullable=true, Order=0)]
        public string edocument
        {
            get
            {
                return this.edocumentField;
            }
            set
            {
                this.edocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public TipoOperacion tipoOperacion
        {
            get
            {
                return this.tipoOperacionField;
            }
            set
            {
                this.tipoOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("patenteAduanal", Order=2)]
        public string[] patenteAduanal
        {
            get
            {
                return this.patenteAduanalField;
            }
            set
            {
                this.patenteAduanalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime fechaExpedicion
        {
            get
            {
                return this.fechaExpedicionField;
            }
            set
            {
                this.fechaExpedicionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rfcConsulta", Order=5)]
        public string[] rfcConsulta
        {
            get
            {
                return this.rfcConsultaField;
            }
            set
            {
                this.rfcConsultaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int tipoFigura
        {
            get
            {
                return this.tipoFiguraField;
            }
            set
            {
                this.tipoFiguraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string correoElectronico
        {
            get
            {
                return this.correoElectronicoField;
            }
            set
            {
                this.correoElectronicoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public FirmaElectronica firmaElectronica
        {
            get
            {
                return this.firmaElectronicaField;
            }
            set
            {
                this.firmaElectronicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public enum TipoOperacion
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TOCE.IMP")]
        TOCEIMP,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("TOCE.EXP")]
        TOCEEXP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class ComprobanteValorElectronicoNoIA : ComprobanteValorElectronicoBase
    {
        
        private string numeroRelacionFacturasField;
        
        private FacturaNoIA[] facturasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroRelacionFacturas
        {
            get
            {
                return this.numeroRelacionFacturasField;
            }
            set
            {
                this.numeroRelacionFacturasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facturas", Order=1)]
        public FacturaNoIA[] facturas
        {
            get
            {
                return this.facturasField;
            }
            set
            {
                this.facturasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FacturaNoIA : FacturaCove
    {
        
        private string numeroFacturaField;
        
        private Emisor emisorField;
        
        private Destinatario destinatarioField;
        
        private Mercancia[] mercanciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroFactura
        {
            get
            {
                return this.numeroFacturaField;
            }
            set
            {
                this.numeroFacturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Emisor emisor
        {
            get
            {
                return this.emisorField;
            }
            set
            {
                this.emisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Destinatario destinatario
        {
            get
            {
                return this.destinatarioField;
            }
            set
            {
                this.destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mercancias", Order=3)]
        public Mercancia[] mercancias
        {
            get
            {
                return this.mercanciasField;
            }
            set
            {
                this.mercanciasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class ComprobanteValorElectronicoIA : ComprobanteValorElectronicoBase
    {
        
        private string numeroRelacionFacturasField;
        
        private Emisor emisorField;
        
        private Destinatario destinatarioField;
        
        private FacturaIA[] facturasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroRelacionFacturas
        {
            get
            {
                return this.numeroRelacionFacturasField;
            }
            set
            {
                this.numeroRelacionFacturasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Emisor emisor
        {
            get
            {
                return this.emisorField;
            }
            set
            {
                this.emisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Destinatario destinatario
        {
            get
            {
                return this.destinatarioField;
            }
            set
            {
                this.destinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facturas", Order=3)]
        public FacturaIA[] facturas
        {
            get
            {
                return this.facturasField;
            }
            set
            {
                this.facturasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FacturaIA : FacturaCove
    {
        
        private string numeroFacturaField;
        
        private Mercancia[] mercanciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroFactura
        {
            get
            {
                return this.numeroFacturaField;
            }
            set
            {
                this.numeroFacturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mercancias", Order=1)]
        public Mercancia[] mercancias
        {
            get
            {
                return this.mercanciasField;
            }
            set
            {
                this.mercanciasField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirCoveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("comprobantes", IsNullable=false)]
        public wsVentanillaUnica.ComprobanteValorElectronico[] solicitarRecibirCoveServicio;
        
        public RecibirCoveRequest()
        {
        }
        
        public RecibirCoveRequest(wsVentanillaUnica.ComprobanteValorElectronico[] solicitarRecibirCoveServicio)
        {
            this.solicitarRecibirCoveServicio = solicitarRecibirCoveServicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirCoveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        public wsVentanillaUnica.Acuse solicitarRecibirCoveServicioResponse;
        
        public RecibirCoveResponse()
        {
        }
        
        public RecibirCoveResponse(wsVentanillaUnica.Acuse solicitarRecibirCoveServicioResponse)
        {
            this.solicitarRecibirCoveServicioResponse = solicitarRecibirCoveServicioResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirRelacionFacturasIARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("comprobantes", IsNullable=false)]
        public wsVentanillaUnica.ComprobanteValorElectronicoIA[] solicitarRecibirRelacionFacturasIAServicio;
        
        public RecibirRelacionFacturasIARequest()
        {
        }
        
        public RecibirRelacionFacturasIARequest(wsVentanillaUnica.ComprobanteValorElectronicoIA[] solicitarRecibirRelacionFacturasIAServicio)
        {
            this.solicitarRecibirRelacionFacturasIAServicio = solicitarRecibirRelacionFacturasIAServicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirRelacionFacturasIAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        public wsVentanillaUnica.Acuse solicitarRecibirRelacionFacturasIAServicioResponse;
        
        public RecibirRelacionFacturasIAResponse()
        {
        }
        
        public RecibirRelacionFacturasIAResponse(wsVentanillaUnica.Acuse solicitarRecibirRelacionFacturasIAServicioResponse)
        {
            this.solicitarRecibirRelacionFacturasIAServicioResponse = solicitarRecibirRelacionFacturasIAServicioResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirRelacionFacturasNoIARequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("comprobantes", IsNullable=false)]
        public wsVentanillaUnica.ComprobanteValorElectronicoNoIA[] solicitarRecibirRelacionFacturasNoIAServicio;
        
        public RecibirRelacionFacturasNoIARequest()
        {
        }
        
        public RecibirRelacionFacturasNoIARequest(wsVentanillaUnica.ComprobanteValorElectronicoNoIA[] solicitarRecibirRelacionFacturasNoIAServicio)
        {
            this.solicitarRecibirRelacionFacturasNoIAServicio = solicitarRecibirRelacionFacturasNoIAServicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecibirRelacionFacturasNoIAResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        public wsVentanillaUnica.Acuse solicitarRecibirRelacionFacturasNoIAServicioResponse;
        
        public RecibirRelacionFacturasNoIAResponse()
        {
        }
        
        public RecibirRelacionFacturasNoIAResponse(wsVentanillaUnica.Acuse solicitarRecibirRelacionFacturasNoIAServicioResponse)
        {
            this.solicitarRecibirRelacionFacturasNoIAServicioResponse = solicitarRecibirRelacionFacturasNoIAServicioResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IReceptorChannel : wsVentanillaUnica.IReceptor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ReceptorClient : System.ServiceModel.ClientBase<wsVentanillaUnica.IReceptor>, wsVentanillaUnica.IReceptor
    {        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReceptorClient() : 
                base(ReceptorClient.GetDefaultBinding(), ReceptorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IReceptorBinding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReceptorClient(EndpointConfiguration endpointConfiguration) : 
                base(ReceptorClient.GetBindingForEndpoint(endpointConfiguration), ReceptorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReceptorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReceptorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReceptorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReceptorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReceptorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }




        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsVentanillaUnica.RecibirCoveResponse> wsVentanillaUnica.IReceptor.RecibirCoveAsync(wsVentanillaUnica.RecibirCoveRequest request)
        {
            return base.Channel.RecibirCoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsVentanillaUnica.RecibirCoveResponse> RecibirCoveAsync(wsVentanillaUnica.ComprobanteValorElectronico[] solicitarRecibirCoveServicio)
        {
            wsVentanillaUnica.RecibirCoveRequest inValue = new wsVentanillaUnica.RecibirCoveRequest();
            inValue.solicitarRecibirCoveServicio = solicitarRecibirCoveServicio;
            return ((wsVentanillaUnica.IReceptor)(this)).RecibirCoveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsVentanillaUnica.RecibirRelacionFacturasIAResponse> wsVentanillaUnica.IReceptor.RecibirRelacionFacturasIAAsync(wsVentanillaUnica.RecibirRelacionFacturasIARequest request)
        {
            return base.Channel.RecibirRelacionFacturasIAAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsVentanillaUnica.RecibirRelacionFacturasIAResponse> RecibirRelacionFacturasIAAsync(wsVentanillaUnica.ComprobanteValorElectronicoIA[] solicitarRecibirRelacionFacturasIAServicio)
        {
            wsVentanillaUnica.RecibirRelacionFacturasIARequest inValue = new wsVentanillaUnica.RecibirRelacionFacturasIARequest();
            inValue.solicitarRecibirRelacionFacturasIAServicio = solicitarRecibirRelacionFacturasIAServicio;
            return ((wsVentanillaUnica.IReceptor)(this)).RecibirRelacionFacturasIAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsVentanillaUnica.RecibirRelacionFacturasNoIAResponse> wsVentanillaUnica.IReceptor.RecibirRelacionFacturasNoIAAsync(wsVentanillaUnica.RecibirRelacionFacturasNoIARequest request)
        {
            return base.Channel.RecibirRelacionFacturasNoIAAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsVentanillaUnica.RecibirRelacionFacturasNoIAResponse> RecibirRelacionFacturasNoIAAsync(wsVentanillaUnica.ComprobanteValorElectronicoNoIA[] solicitarRecibirRelacionFacturasNoIAServicio)
        {
            wsVentanillaUnica.RecibirRelacionFacturasNoIARequest inValue = new wsVentanillaUnica.RecibirRelacionFacturasNoIARequest();
            inValue.solicitarRecibirRelacionFacturasNoIAServicio = solicitarRecibirRelacionFacturasNoIAServicio;
            return ((wsVentanillaUnica.IReceptor)(this)).RecibirRelacionFacturasNoIAAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IReceptorBinding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportWithMessageCredential;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IReceptorBinding))
            {
                return new System.ServiceModel.EndpointAddress("https://www.ventanillaunica.gob.mx:8110/ventanilla/RecibirCoveService");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReceptorClient.GetBindingForEndpoint(EndpointConfiguration.IReceptorBinding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReceptorClient.GetEndpointAddress(EndpointConfiguration.IReceptorBinding);
        }
        
        public enum EndpointConfiguration
        {
            
            IReceptorBinding,
        }
    }
}
