//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsCentralizar
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentosPorGuia", Namespace="http://schemas.datacontract.org/2004/07/SistemaDePedimentos.Entidades")]
    public partial class DocumentosPorGuia : object
    {
        
        private int ConsecutivoField;
        
        private string ExtensionField;
        
        private System.DateTime FechaAltaField;
        
        private int IdUsuarioField;
        
        private string RutaFechaField;
        
        private string RutaS3Field;
        
        private bool S3Field;
        
        private int idDocumentoField;
        
        private int idReferenciaField;
        
        private int idTipoDocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Consecutivo
        {
            get
            {
                return this.ConsecutivoField;
            }
            set
            {
                this.ConsecutivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAlta
        {
            get
            {
                return this.FechaAltaField;
            }
            set
            {
                this.FechaAltaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaFecha
        {
            get
            {
                return this.RutaFechaField;
            }
            set
            {
                this.RutaFechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaS3
        {
            get
            {
                return this.RutaS3Field;
            }
            set
            {
                this.RutaS3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool S3
        {
            get
            {
                return this.S3Field;
            }
            set
            {
                this.S3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDocumento
        {
            get
            {
                return this.idDocumentoField;
            }
            set
            {
                this.idDocumentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idReferencia
        {
            get
            {
                return this.idReferenciaField;
            }
            set
            {
                this.idReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTipoDocumento
        {
            get
            {
                return this.idTipoDocumentoField;
            }
            set
            {
                this.idTipoDocumentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuariosDisponibles", Namespace="http://schemas.datacontract.org/2004/07/SistemaDePedimentos.Entidades")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsCentralizar.CatalogoDeUsuarios))]
    public partial class UsuariosDisponibles : object
    {
        
        private System.DateTime FechaField;
        
        private int IdDepartamentoField;
        
        private int IdOficinaField;
        
        private int IdUsuarioField;
        
        private int IdUsuarioDisponibleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepartamento
        {
            get
            {
                return this.IdDepartamentoField;
            }
            set
            {
                this.IdDepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOficina
        {
            get
            {
                return this.IdOficinaField;
            }
            set
            {
                this.IdOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioDisponible
        {
            get
            {
                return this.IdUsuarioDisponibleField;
            }
            set
            {
                this.IdUsuarioDisponibleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoDeUsuarios", Namespace="http://schemas.datacontract.org/2004/07/SistemaDePedimentos.Entidades")]
    public partial class CatalogoDeUsuarios : wsCentralizar.UsuariosDisponibles
    {
        
        private string AnteriorField;
        
        private bool AutorizaegresoField;
        
        private System.DateTime BajaField;
        
        private string CURPField;
        
        private int CapturoUsuarioField;
        
        private string EmailField;
        
        private bool EsUnClienteField;
        
        private string ExtensionTelField;
        
        private System.DateTime FechaDeCapturaField;
        
        private byte FotoField;
        
        private int IDDatosDeEmpresaField;
        
        private int IDGeneroField;
        
        private int IDGrupoField;
        
        private int IDPuestoField;
        
        private int IdEstacionDefaultField;
        
        private int IdModuloField;
        
        private System.DateTime IngresoANominaField;
        
        private System.DateTime IngresoRealField;
        
        private string InicialesField;
        
        private double MontodeAutorizacionField;
        
        private bool MostrarTodosLosEventosField;
        
        private string NombreField;
        
        private int NumeroDeEmpleadoField;
        
        private wsCentralizar.CatalogoDeOficinas OficinaField;
        
        private int OperacionField;
        
        private bool PermitirVariosExpertitField;
        
        private int PoolPendientesField;
        
        private string PrimeroField;
        
        private string PswField;
        
        private string SiguienteField;
        
        private bool SolicitarCambioDePasswordField;
        
        private string TelParticularField;
        
        private bool TomarTelPartField;
        
        private string UltimoField;
        
        private string UsuarioField;
        
        private bool UsuarioActivoField;
        
        private string UsuarioCASAField;
        
        private string UsuarioWindowsField;
        
        private bool UsuarioautomaticoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anterior
        {
            get
            {
                return this.AnteriorField;
            }
            set
            {
                this.AnteriorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Autorizaegreso
        {
            get
            {
                return this.AutorizaegresoField;
            }
            set
            {
                this.AutorizaegresoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Baja
        {
            get
            {
                return this.BajaField;
            }
            set
            {
                this.BajaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CURP
        {
            get
            {
                return this.CURPField;
            }
            set
            {
                this.CURPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CapturoUsuario
        {
            get
            {
                return this.CapturoUsuarioField;
            }
            set
            {
                this.CapturoUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsUnCliente
        {
            get
            {
                return this.EsUnClienteField;
            }
            set
            {
                this.EsUnClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtensionTel
        {
            get
            {
                return this.ExtensionTelField;
            }
            set
            {
                this.ExtensionTelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaDeCaptura
        {
            get
            {
                return this.FechaDeCapturaField;
            }
            set
            {
                this.FechaDeCapturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                this.FotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDDatosDeEmpresa
        {
            get
            {
                return this.IDDatosDeEmpresaField;
            }
            set
            {
                this.IDDatosDeEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDGenero
        {
            get
            {
                return this.IDGeneroField;
            }
            set
            {
                this.IDGeneroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDGrupo
        {
            get
            {
                return this.IDGrupoField;
            }
            set
            {
                this.IDGrupoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPuesto
        {
            get
            {
                return this.IDPuestoField;
            }
            set
            {
                this.IDPuestoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEstacionDefault
        {
            get
            {
                return this.IdEstacionDefaultField;
            }
            set
            {
                this.IdEstacionDefaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdModulo
        {
            get
            {
                return this.IdModuloField;
            }
            set
            {
                this.IdModuloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IngresoANomina
        {
            get
            {
                return this.IngresoANominaField;
            }
            set
            {
                this.IngresoANominaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IngresoReal
        {
            get
            {
                return this.IngresoRealField;
            }
            set
            {
                this.IngresoRealField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iniciales
        {
            get
            {
                return this.InicialesField;
            }
            set
            {
                this.InicialesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MontodeAutorizacion
        {
            get
            {
                return this.MontodeAutorizacionField;
            }
            set
            {
                this.MontodeAutorizacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MostrarTodosLosEventos
        {
            get
            {
                return this.MostrarTodosLosEventosField;
            }
            set
            {
                this.MostrarTodosLosEventosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroDeEmpleado
        {
            get
            {
                return this.NumeroDeEmpleadoField;
            }
            set
            {
                this.NumeroDeEmpleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wsCentralizar.CatalogoDeOficinas Oficina
        {
            get
            {
                return this.OficinaField;
            }
            set
            {
                this.OficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Operacion
        {
            get
            {
                return this.OperacionField;
            }
            set
            {
                this.OperacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PermitirVariosExpertit
        {
            get
            {
                return this.PermitirVariosExpertitField;
            }
            set
            {
                this.PermitirVariosExpertitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PoolPendientes
        {
            get
            {
                return this.PoolPendientesField;
            }
            set
            {
                this.PoolPendientesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Primero
        {
            get
            {
                return this.PrimeroField;
            }
            set
            {
                this.PrimeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Psw
        {
            get
            {
                return this.PswField;
            }
            set
            {
                this.PswField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Siguiente
        {
            get
            {
                return this.SiguienteField;
            }
            set
            {
                this.SiguienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SolicitarCambioDePassword
        {
            get
            {
                return this.SolicitarCambioDePasswordField;
            }
            set
            {
                this.SolicitarCambioDePasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelParticular
        {
            get
            {
                return this.TelParticularField;
            }
            set
            {
                this.TelParticularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TomarTelPart
        {
            get
            {
                return this.TomarTelPartField;
            }
            set
            {
                this.TomarTelPartField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ultimo
        {
            get
            {
                return this.UltimoField;
            }
            set
            {
                this.UltimoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UsuarioActivo
        {
            get
            {
                return this.UsuarioActivoField;
            }
            set
            {
                this.UsuarioActivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCASA
        {
            get
            {
                return this.UsuarioCASAField;
            }
            set
            {
                this.UsuarioCASAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioWindows
        {
            get
            {
                return this.UsuarioWindowsField;
            }
            set
            {
                this.UsuarioWindowsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Usuarioautomatico
        {
            get
            {
                return this.UsuarioautomaticoField;
            }
            set
            {
                this.UsuarioautomaticoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogoDeOficinas", Namespace="http://schemas.datacontract.org/2004/07/SistemaDePedimentos.Entidades")]
    public partial class CatalogoDeOficinas : object
    {
        
        private bool ActCCFirmasField;
        
        private bool ActImprimeManifField;
        
        private bool ActImprimePedField;
        
        private string AduDespField;
        
        private string AduEntrField;
        
        private int AutomaticoConsolField;
        
        private string ClaveGatewayField;
        
        private string ClienteMensajeriaField;
        
        private string CveMantField;
        
        private string CvePrevField;
        
        private bool DHLField;
        
        private int DesOrigField;
        
        private string DescripcionField;
        
        private string E_MailField;
        
        private string EmpFacField;
        
        private bool GenImprimeManifField;
        
        private bool GenImprimePedField;
        
        private bool HabilitarWebField;
        
        private string HostField;
        
        private int IDDatosDeEmpresaField;
        
        private int IdOficinaField;
        
        private int IdOficinaExtraField;
        
        private double LimiteDePagoElectronicoField;
        
        private int MtrArriExpField;
        
        private int MtrArriImpField;
        
        private int MtrEntrExpField;
        
        private int MtrEntrImpField;
        
        private int MtrSaliExpField;
        
        private int MtrSaliImpField;
        
        private int OperacionDefaultField;
        
        private bool PantallaActivaField;
        
        private string PassMailField;
        
        private string PatenteDefaultField;
        
        private int PuertoField;
        
        private string RutaDigitalizadosVucemField;
        
        private string RutaPantallasField;
        
        private double SalarioMinimoField;
        
        private int SecDespField;
        
        private bool UsarWSWecField;
        
        private bool UsarWsDigitalizadosField;
        
        private bool UtilizaGPField;
        
        private bool ValidaUltimaVersionField;
        
        private bool ValidacionAutomaticaField;
        
        private string VersionModuloTraficoField;
        
        private string idAduanaField;
        
        private bool ironPDFField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ActCCFirmas
        {
            get
            {
                return this.ActCCFirmasField;
            }
            set
            {
                this.ActCCFirmasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ActImprimeManif
        {
            get
            {
                return this.ActImprimeManifField;
            }
            set
            {
                this.ActImprimeManifField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ActImprimePed
        {
            get
            {
                return this.ActImprimePedField;
            }
            set
            {
                this.ActImprimePedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AduDesp
        {
            get
            {
                return this.AduDespField;
            }
            set
            {
                this.AduDespField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AduEntr
        {
            get
            {
                return this.AduEntrField;
            }
            set
            {
                this.AduEntrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutomaticoConsol
        {
            get
            {
                return this.AutomaticoConsolField;
            }
            set
            {
                this.AutomaticoConsolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaveGateway
        {
            get
            {
                return this.ClaveGatewayField;
            }
            set
            {
                this.ClaveGatewayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClienteMensajeria
        {
            get
            {
                return this.ClienteMensajeriaField;
            }
            set
            {
                this.ClienteMensajeriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CveMant
        {
            get
            {
                return this.CveMantField;
            }
            set
            {
                this.CveMantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CvePrev
        {
            get
            {
                return this.CvePrevField;
            }
            set
            {
                this.CvePrevField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DHL
        {
            get
            {
                return this.DHLField;
            }
            set
            {
                this.DHLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DesOrig
        {
            get
            {
                return this.DesOrigField;
            }
            set
            {
                this.DesOrigField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string E_Mail
        {
            get
            {
                return this.E_MailField;
            }
            set
            {
                this.E_MailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmpFac
        {
            get
            {
                return this.EmpFacField;
            }
            set
            {
                this.EmpFacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GenImprimeManif
        {
            get
            {
                return this.GenImprimeManifField;
            }
            set
            {
                this.GenImprimeManifField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool GenImprimePed
        {
            get
            {
                return this.GenImprimePedField;
            }
            set
            {
                this.GenImprimePedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HabilitarWeb
        {
            get
            {
                return this.HabilitarWebField;
            }
            set
            {
                this.HabilitarWebField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Host
        {
            get
            {
                return this.HostField;
            }
            set
            {
                this.HostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDDatosDeEmpresa
        {
            get
            {
                return this.IDDatosDeEmpresaField;
            }
            set
            {
                this.IDDatosDeEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOficina
        {
            get
            {
                return this.IdOficinaField;
            }
            set
            {
                this.IdOficinaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdOficinaExtra
        {
            get
            {
                return this.IdOficinaExtraField;
            }
            set
            {
                this.IdOficinaExtraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LimiteDePagoElectronico
        {
            get
            {
                return this.LimiteDePagoElectronicoField;
            }
            set
            {
                this.LimiteDePagoElectronicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MtrArriExp
        {
            get
            {
                return this.MtrArriExpField;
            }
            set
            {
                this.MtrArriExpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MtrArriImp
        {
            get
            {
                return this.MtrArriImpField;
            }
            set
            {
                this.MtrArriImpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MtrEntrExp
        {
            get
            {
                return this.MtrEntrExpField;
            }
            set
            {
                this.MtrEntrExpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MtrEntrImp
        {
            get
            {
                return this.MtrEntrImpField;
            }
            set
            {
                this.MtrEntrImpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MtrSaliExp
        {
            get
            {
                return this.MtrSaliExpField;
            }
            set
            {
                this.MtrSaliExpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MtrSaliImp
        {
            get
            {
                return this.MtrSaliImpField;
            }
            set
            {
                this.MtrSaliImpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperacionDefault
        {
            get
            {
                return this.OperacionDefaultField;
            }
            set
            {
                this.OperacionDefaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PantallaActiva
        {
            get
            {
                return this.PantallaActivaField;
            }
            set
            {
                this.PantallaActivaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassMail
        {
            get
            {
                return this.PassMailField;
            }
            set
            {
                this.PassMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PatenteDefault
        {
            get
            {
                return this.PatenteDefaultField;
            }
            set
            {
                this.PatenteDefaultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puerto
        {
            get
            {
                return this.PuertoField;
            }
            set
            {
                this.PuertoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaDigitalizadosVucem
        {
            get
            {
                return this.RutaDigitalizadosVucemField;
            }
            set
            {
                this.RutaDigitalizadosVucemField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RutaPantallas
        {
            get
            {
                return this.RutaPantallasField;
            }
            set
            {
                this.RutaPantallasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SalarioMinimo
        {
            get
            {
                return this.SalarioMinimoField;
            }
            set
            {
                this.SalarioMinimoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecDesp
        {
            get
            {
                return this.SecDespField;
            }
            set
            {
                this.SecDespField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UsarWSWec
        {
            get
            {
                return this.UsarWSWecField;
            }
            set
            {
                this.UsarWSWecField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UsarWsDigitalizados
        {
            get
            {
                return this.UsarWsDigitalizadosField;
            }
            set
            {
                this.UsarWsDigitalizadosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UtilizaGP
        {
            get
            {
                return this.UtilizaGPField;
            }
            set
            {
                this.UtilizaGPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ValidaUltimaVersion
        {
            get
            {
                return this.ValidaUltimaVersionField;
            }
            set
            {
                this.ValidaUltimaVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ValidacionAutomatica
        {
            get
            {
                return this.ValidacionAutomaticaField;
            }
            set
            {
                this.ValidacionAutomaticaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VersionModuloTrafico
        {
            get
            {
                return this.VersionModuloTraficoField;
            }
            set
            {
                this.VersionModuloTraficoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idAduana
        {
            get
            {
                return this.idAduanaField;
            }
            set
            {
                this.idAduanaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ironPDF
        {
            get
            {
                return this.ironPDFField;
            }
            set
            {
                this.ironPDFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="wsRespuestaDespachos", Namespace="http://schemas.datacontract.org/2004/07/WcfDocumentos")]
    public partial class wsRespuestaDespachos : object
    {
        
        private bool ExisteErrorField;
        
        private string LinkField;
        
        private string msgErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExisteError
        {
            get
            {
                return this.ExisteErrorField;
            }
            set
            {
                this.ExisteErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link
        {
            get
            {
                return this.LinkField;
            }
            set
            {
                this.LinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msgError
        {
            get
            {
                return this.msgErrorField;
            }
            set
            {
                this.msgErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="respuestaWS", Namespace="http://schemas.datacontract.org/2004/07/SistemaDePedimentos")]
    public partial class respuestaWS : object
    {
        
        private bool ExisteErrorField;
        
        private string msgErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ExisteError
        {
            get
            {
                return this.ExisteErrorField;
            }
            set
            {
                this.ExisteErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msgError
        {
            get
            {
                return this.msgErrorField;
            }
            set
            {
                this.msgErrorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsCentralizar.IwsDocumentos")]
    public interface IwsDocumentos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/CentralizarDocumentos", ReplyAction="http://tempuri.org/IwsDocumentos/CentralizarDocumentosResponse")]
        System.Threading.Tasks.Task<bool> CentralizarDocumentosAsync(byte[] lArchivo, string lPath, string lNombreArchivo, string lExtension, bool SobreEscribir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/CentralizarDocumentosporGuia", ReplyAction="http://tempuri.org/IwsDocumentos/CentralizarDocumentosporGuiaResponse")]
        System.Threading.Tasks.Task<bool> CentralizarDocumentosporGuiaAsync(byte[] lArchivo, string lPath, string lNombreArchivo, string lExtension, bool SobreEscribir, wsCentralizar.DocumentosPorGuia objDocumentosporguia, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/CentralizarDocumentosNew", ReplyAction="http://tempuri.org/IwsDocumentos/CentralizarDocumentosNewResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsCentralizar.wsRespuestaDespachos))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsCentralizar.respuestaWS))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsCentralizar.DocumentosPorGuia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsCentralizar.CatalogoDeUsuarios))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsCentralizar.UsuariosDisponibles))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(wsCentralizar.CatalogoDeOficinas))]
        System.Threading.Tasks.Task<object> CentralizarDocumentosNewAsync(byte[] lArchivo, string lPath, string lNombreArchivo, string lExtension, bool SobreEscribir, wsCentralizar.CatalogoDeUsuarios ObjUsuario, string Referencia, int IdDocumentoGP, string MyConnectionStringGP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/EliminarDocumentos", ReplyAction="http://tempuri.org/IwsDocumentos/EliminarDocumentosResponse")]
        System.Threading.Tasks.Task<bool> EliminarDocumentosAsync(string lPath, string lNombreArchivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/GenerarPDF", ReplyAction="http://tempuri.org/IwsDocumentos/GenerarPDFResponse")]
        System.Threading.Tasks.Task<bool> GenerarPDFAsync(string Referencia, bool Simplificado, bool subirFTP, int IdFTP, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/BuscarGuiayFactura", ReplyAction="http://tempuri.org/IwsDocumentos/BuscarGuiayFacturaResponse")]
        System.Threading.Tasks.Task<bool> BuscarGuiayFacturaAsync(string GuiaHouse, int IDDatosDeEmpresa, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/ConvertirPDFdpi", ReplyAction="http://tempuri.org/IwsDocumentos/ConvertirPDFdpiResponse")]
        System.Threading.Tasks.Task<string> ConvertirPDFdpiAsync(string Path, string lArchivo, byte[] Archivo, string Extension, int IdUsuario, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/ConvertirPDFdpiNuevo", ReplyAction="http://tempuri.org/IwsDocumentos/ConvertirPDFdpiNuevoResponse")]
        System.Threading.Tasks.Task<string> ConvertirPDFdpiNuevoAsync(string Path, string lArchivo, byte[] Archivo, string Extension, int IdUsuario, string UbicacionVucem, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/DescargarDocumento", ReplyAction="http://tempuri.org/IwsDocumentos/DescargarDocumentoResponse")]
        System.Threading.Tasks.Task<byte[]> DescargarDocumentoAsync(string Archivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/GenerarExpediente", ReplyAction="http://tempuri.org/IwsDocumentos/GenerarExpedienteResponse")]
        System.Threading.Tasks.Task<wsCentralizar.respuestaWS> GenerarExpedienteAsync(int IdReferencia, int IdUsuario, int IdDepartamento, int IdOficina, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/GenerarExpedienteDocExtra", ReplyAction="http://tempuri.org/IwsDocumentos/GenerarExpedienteDocExtraResponse")]
        System.Threading.Tasks.Task<bool> GenerarExpedienteDocExtraAsync(int IdReferencia, byte[] Archivo, int IdUsuario, int IdDepartamento, int IdOficina, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/ConviertePDF", ReplyAction="http://tempuri.org/IwsDocumentos/ConviertePDFResponse")]
        System.Threading.Tasks.Task<string> ConviertePDFAsync(string Origen, string Destino, string TipoConversion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/SellarGuia", ReplyAction="http://tempuri.org/IwsDocumentos/SellarGuiaResponse")]
        System.Threading.Tasks.Task<string> SellarGuiaAsync(int IdConsolMaster, string ArchivoGuia, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/SubirArchivo", ReplyAction="http://tempuri.org/IwsDocumentos/SubirArchivoResponse")]
        System.Threading.Tasks.Task<string> SubirArchivoAsync(string lArchivo, byte[] Archivo, string Extension, bool Combinar, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/ConvertirImagenenPDF", ReplyAction="http://tempuri.org/IwsDocumentos/ConvertirImagenenPDFResponse")]
        System.Threading.Tasks.Task<string> ConvertirImagenenPDFAsync(string lArchivoaConvertir, int IdUsuario, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/ConvertirFacturaaPDF", ReplyAction="http://tempuri.org/IwsDocumentos/ConvertirFacturaaPDFResponse")]
        System.Threading.Tasks.Task ConvertirFacturaaPDFAsync(string Referencia, int IDDatosDeEmpresa, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/EliminaDocumento", ReplyAction="http://tempuri.org/IwsDocumentos/EliminaDocumentoResponse")]
        System.Threading.Tasks.Task EliminaDocumentoAsync(int IdDocumento, string RutaFisica, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/ExisteDocumento", ReplyAction="http://tempuri.org/IwsDocumentos/ExisteDocumentoResponse")]
        System.Threading.Tasks.Task<bool> ExisteDocumentoAsync(string Archivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/CombinareDocuments", ReplyAction="http://tempuri.org/IwsDocumentos/CombinareDocumentsResponse")]
        System.Threading.Tasks.Task<byte[]> CombinareDocumentsAsync(int idReferencia, int IDDatosDeEmpresa, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/GenerarProforma", ReplyAction="http://tempuri.org/IwsDocumentos/GenerarProformaResponse")]
        System.Threading.Tasks.Task<wsCentralizar.respuestaWS> GenerarProformaAsync(int idReferencia, bool Simplificado, bool Proforma, int IDDatosDeEmpresa, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/DocumentosAlmacen", ReplyAction="http://tempuri.org/IwsDocumentos/DocumentosAlmacenResponse")]
        System.Threading.Tasks.Task<byte[]> DocumentosAlmacenAsync(int idReferencia, bool DHL, int IDDatosDeEmpresa, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/MoverGuiayFactura", ReplyAction="http://tempuri.org/IwsDocumentos/MoverGuiayFacturaResponse")]
        System.Threading.Tasks.Task<wsCentralizar.respuestaWS> MoverGuiayFacturaAsync(string ReferenciaOrigen, string ReferenciaDestino, int IDDatosDeEmpresa, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/DocumentoDespachos", ReplyAction="http://tempuri.org/IwsDocumentos/DocumentoDespachosResponse")]
        System.Threading.Tasks.Task<wsCentralizar.wsRespuestaDespachos> DocumentoDespachosAsync(int IdUsuario, string MyConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IwsDocumentos/DocumentoDespachosIdRelacion", ReplyAction="http://tempuri.org/IwsDocumentos/DocumentoDespachosIdRelacionResponse")]
        System.Threading.Tasks.Task<wsCentralizar.wsRespuestaDespachos> DocumentoDespachosIdRelacionAsync(int IdRelacionWec, int IdUsuario, string MyConnectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IwsDocumentosChannel : wsCentralizar.IwsDocumentos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class IwsDocumentosClient : System.ServiceModel.ClientBase<wsCentralizar.IwsDocumentos>, wsCentralizar.IwsDocumentos
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IwsDocumentosClient() : 
                base(IwsDocumentosClient.GetDefaultBinding(), IwsDocumentosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IwsDocumentos.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IwsDocumentosClient(EndpointConfiguration endpointConfiguration) : 
                base(IwsDocumentosClient.GetBindingForEndpoint(endpointConfiguration), IwsDocumentosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IwsDocumentosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IwsDocumentosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IwsDocumentosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IwsDocumentosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IwsDocumentosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> CentralizarDocumentosAsync(byte[] lArchivo, string lPath, string lNombreArchivo, string lExtension, bool SobreEscribir)
        {
            return base.Channel.CentralizarDocumentosAsync(lArchivo, lPath, lNombreArchivo, lExtension, SobreEscribir);
        }
        
        public System.Threading.Tasks.Task<bool> CentralizarDocumentosporGuiaAsync(byte[] lArchivo, string lPath, string lNombreArchivo, string lExtension, bool SobreEscribir, wsCentralizar.DocumentosPorGuia objDocumentosporguia, string MyConnectionString)
        {
            return base.Channel.CentralizarDocumentosporGuiaAsync(lArchivo, lPath, lNombreArchivo, lExtension, SobreEscribir, objDocumentosporguia, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<object> CentralizarDocumentosNewAsync(byte[] lArchivo, string lPath, string lNombreArchivo, string lExtension, bool SobreEscribir, wsCentralizar.CatalogoDeUsuarios ObjUsuario, string Referencia, int IdDocumentoGP, string MyConnectionStringGP)
        {
            return base.Channel.CentralizarDocumentosNewAsync(lArchivo, lPath, lNombreArchivo, lExtension, SobreEscribir, ObjUsuario, Referencia, IdDocumentoGP, MyConnectionStringGP);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarDocumentosAsync(string lPath, string lNombreArchivo)
        {
            return base.Channel.EliminarDocumentosAsync(lPath, lNombreArchivo);
        }
        
        public System.Threading.Tasks.Task<bool> GenerarPDFAsync(string Referencia, bool Simplificado, bool subirFTP, int IdFTP, string MyConnectionString)
        {
            return base.Channel.GenerarPDFAsync(Referencia, Simplificado, subirFTP, IdFTP, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<bool> BuscarGuiayFacturaAsync(string GuiaHouse, int IDDatosDeEmpresa, string MyConnectionString)
        {
            return base.Channel.BuscarGuiayFacturaAsync(GuiaHouse, IDDatosDeEmpresa, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> ConvertirPDFdpiAsync(string Path, string lArchivo, byte[] Archivo, string Extension, int IdUsuario, string MyConnectionString)
        {
            return base.Channel.ConvertirPDFdpiAsync(Path, lArchivo, Archivo, Extension, IdUsuario, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> ConvertirPDFdpiNuevoAsync(string Path, string lArchivo, byte[] Archivo, string Extension, int IdUsuario, string UbicacionVucem, string MyConnectionString)
        {
            return base.Channel.ConvertirPDFdpiNuevoAsync(Path, lArchivo, Archivo, Extension, IdUsuario, UbicacionVucem, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<byte[]> DescargarDocumentoAsync(string Archivo)
        {
            return base.Channel.DescargarDocumentoAsync(Archivo);
        }
        
        public System.Threading.Tasks.Task<wsCentralizar.respuestaWS> GenerarExpedienteAsync(int IdReferencia, int IdUsuario, int IdDepartamento, int IdOficina, string MyConnectionString)
        {
            return base.Channel.GenerarExpedienteAsync(IdReferencia, IdUsuario, IdDepartamento, IdOficina, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<bool> GenerarExpedienteDocExtraAsync(int IdReferencia, byte[] Archivo, int IdUsuario, int IdDepartamento, int IdOficina, string MyConnectionString)
        {
            return base.Channel.GenerarExpedienteDocExtraAsync(IdReferencia, Archivo, IdUsuario, IdDepartamento, IdOficina, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> ConviertePDFAsync(string Origen, string Destino, string TipoConversion)
        {
            return base.Channel.ConviertePDFAsync(Origen, Destino, TipoConversion);
        }
        
        public System.Threading.Tasks.Task<string> SellarGuiaAsync(int IdConsolMaster, string ArchivoGuia, string MyConnectionString)
        {
            return base.Channel.SellarGuiaAsync(IdConsolMaster, ArchivoGuia, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> SubirArchivoAsync(string lArchivo, byte[] Archivo, string Extension, bool Combinar, string MyConnectionString)
        {
            return base.Channel.SubirArchivoAsync(lArchivo, Archivo, Extension, Combinar, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<string> ConvertirImagenenPDFAsync(string lArchivoaConvertir, int IdUsuario, string MyConnectionString)
        {
            return base.Channel.ConvertirImagenenPDFAsync(lArchivoaConvertir, IdUsuario, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task ConvertirFacturaaPDFAsync(string Referencia, int IDDatosDeEmpresa, string MyConnectionString)
        {
            return base.Channel.ConvertirFacturaaPDFAsync(Referencia, IDDatosDeEmpresa, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task EliminaDocumentoAsync(int IdDocumento, string RutaFisica, string MyConnectionString)
        {
            return base.Channel.EliminaDocumentoAsync(IdDocumento, RutaFisica, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteDocumentoAsync(string Archivo)
        {
            return base.Channel.ExisteDocumentoAsync(Archivo);
        }
        
        public System.Threading.Tasks.Task<byte[]> CombinareDocumentsAsync(int idReferencia, int IDDatosDeEmpresa, string MyConnectionString)
        {
            return base.Channel.CombinareDocumentsAsync(idReferencia, IDDatosDeEmpresa, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<wsCentralizar.respuestaWS> GenerarProformaAsync(int idReferencia, bool Simplificado, bool Proforma, int IDDatosDeEmpresa, string MyConnectionString)
        {
            return base.Channel.GenerarProformaAsync(idReferencia, Simplificado, Proforma, IDDatosDeEmpresa, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<byte[]> DocumentosAlmacenAsync(int idReferencia, bool DHL, int IDDatosDeEmpresa, string MyConnectionString)
        {
            return base.Channel.DocumentosAlmacenAsync(idReferencia, DHL, IDDatosDeEmpresa, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<wsCentralizar.respuestaWS> MoverGuiayFacturaAsync(string ReferenciaOrigen, string ReferenciaDestino, int IDDatosDeEmpresa, string MyConnectionString)
        {
            return base.Channel.MoverGuiayFacturaAsync(ReferenciaOrigen, ReferenciaDestino, IDDatosDeEmpresa, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<wsCentralizar.wsRespuestaDespachos> DocumentoDespachosAsync(int IdUsuario, string MyConnectionString)
        {
            return base.Channel.DocumentoDespachosAsync(IdUsuario, MyConnectionString);
        }
        
        public System.Threading.Tasks.Task<wsCentralizar.wsRespuestaDespachos> DocumentoDespachosIdRelacionAsync(int IdRelacionWec, int IdUsuario, string MyConnectionString)
        {
            return base.Channel.DocumentoDespachosIdRelacionAsync(IdRelacionWec, IdUsuario, MyConnectionString);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IwsDocumentos))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IwsDocumentos))
            {
                return new System.ServiceModel.EndpointAddress("http://www.expertti-web.com.mx:83/wsDocumentos.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IwsDocumentosClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IwsDocumentos);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IwsDocumentosClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IwsDocumentos);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IwsDocumentos,
        }
    }
}
