//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using LibreriaClasesAPIExpertti.Utilities.Helper;

namespace wsRespuestaCove
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/service/", ConfigurationName="wsRespuestaCove.IReceptor")]
    public interface IReceptor
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ventanillaunica.gob.mx/ConsultarRespuestaCove", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<wsRespuestaCove.ConsultarRespuestaCoveResponse> ConsultarRespuestaCoveAsync(wsRespuestaCove.ConsultarRespuestaCoveRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class SolicitarConsultarRespuestaCoveServicio
    {
        
        private string numeroOperacionField;
        
        private FirmaElectronica firmaElectronicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroOperacion
        {
            get
            {
                return this.numeroOperacionField;
            }
            set
            {
                this.numeroOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FirmaElectronica firmaElectronica
        {
            get
            {
                return this.firmaElectronicaField;
            }
            set
            {
                this.firmaElectronicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class FirmaElectronica
    {
        
        private byte[] certificadoField;
        
        private string cadenaOriginalField;
        
        private byte[] firmaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] certificado
        {
            get
            {
                return this.certificadoField;
            }
            set
            {
                this.certificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cadenaOriginal
        {
            get
            {
                return this.cadenaOriginalField;
            }
            set
            {
                this.cadenaOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] firma
        {
            get
            {
                return this.firmaField;
            }
            set
            {
                this.firmaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class RespuestaOperacion
    {
        
        private string numeroFacturaORelacionFacturasField;
        
        private bool contieneErrorField;
        
        private string eDocumentField;
        
        private string numeroAdendaField;
        
        private string[] erroresField;
        
        private string cadenaOriginalField;
        
        private string selloDigitalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string numeroFacturaORelacionFacturas
        {
            get
            {
                return this.numeroFacturaORelacionFacturasField;
            }
            set
            {
                this.numeroFacturaORelacionFacturasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool contieneError
        {
            get
            {
                return this.contieneErrorField;
            }
            set
            {
                this.contieneErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string eDocument
        {
            get
            {
                return this.eDocumentField;
            }
            set
            {
                this.eDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string numeroAdenda
        {
            get
            {
                return this.numeroAdendaField;
            }
            set
            {
                this.numeroAdendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("mensaje", IsNullable=false)]
        public string[] errores
        {
            get
            {
                return this.erroresField;
            }
            set
            {
                this.erroresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string cadenaOriginal
        {
            get
            {
                return this.cadenaOriginalField;
            }
            set
            {
                this.cadenaOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string selloDigital
        {
            get
            {
                return this.selloDigitalField;
            }
            set
            {
                this.selloDigitalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/")]
    public partial class RespuestaPeticion
    {
        
        private string numeroOperacionField;
        
        private System.DateTime horaRecepcionField;
        
        private RespuestaOperacion[] respuestasOperacionesField;
        
        private string leyendaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroOperacion
        {
            get
            {
                return this.numeroOperacionField;
            }
            set
            {
                this.numeroOperacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime horaRecepcion
        {
            get
            {
                return this.horaRecepcionField;
            }
            set
            {
                this.horaRecepcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("respuestasOperaciones", Order=2)]
        public RespuestaOperacion[] respuestasOperaciones
        {
            get
            {
                return this.respuestasOperacionesField;
            }
            set
            {
                this.respuestasOperacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string leyenda
        {
            get
            {
                return this.leyendaField;
            }
            set
            {
                this.leyendaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRespuestaCoveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        public wsRespuestaCove.SolicitarConsultarRespuestaCoveServicio solicitarConsultarRespuestaCoveServicio;
        
        public ConsultarRespuestaCoveRequest()
        {
        }
        
        public ConsultarRespuestaCoveRequest(wsRespuestaCove.SolicitarConsultarRespuestaCoveServicio solicitarConsultarRespuestaCoveServicio)
        {
            this.solicitarConsultarRespuestaCoveServicio = solicitarConsultarRespuestaCoveServicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarRespuestaCoveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.ventanillaunica.gob.mx/cove/ws/oxml/", Order=0)]
        public wsRespuestaCove.RespuestaPeticion solicitarConsultarRespuestaCoveServicioResponse;
        public ConsultarRespuestaCoveResponse()
        {
        }
        
        public ConsultarRespuestaCoveResponse(wsRespuestaCove.RespuestaPeticion solicitarConsultarRespuestaCoveServicioResponse)
        {
            this.solicitarConsultarRespuestaCoveServicioResponse = solicitarConsultarRespuestaCoveServicioResponse;
        }



    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IReceptorChannel : wsRespuestaCove.IReceptor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ReceptorClient : System.ServiceModel.ClientBase<wsRespuestaCove.IReceptor>, wsRespuestaCove.IReceptor
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReceptorClient() : 
                base(ReceptorClient.GetDefaultBinding(), ReceptorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IReceptorBinding.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReceptorClient(EndpointConfiguration endpointConfiguration) : 
                base(ReceptorClient.GetBindingForEndpoint(endpointConfiguration), ReceptorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReceptorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReceptorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReceptorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReceptorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReceptorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }

        public async Task<wsRespuestaCove.RespuestaPeticion> ConsultarRespuestaCove(wsRespuestaCove.SolicitarConsultarRespuestaCoveServicio solicitarConsultarRespuestaCoveServicio)
        {
            var inValue = new wsRespuestaCove.ConsultarRespuestaCoveRequest();
            inValue.solicitarConsultarRespuestaCoveServicio = solicitarConsultarRespuestaCoveServicio;

            var retVal = await ((wsRespuestaCove.IReceptor)this).ConsultarRespuestaCoveAsync(inValue);

            return retVal.solicitarConsultarRespuestaCoveServicioResponse;
        }


        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsRespuestaCove.ConsultarRespuestaCoveResponse> wsRespuestaCove.IReceptor.ConsultarRespuestaCoveAsync(wsRespuestaCove.ConsultarRespuestaCoveRequest request)
        {
            return base.Channel.ConsultarRespuestaCoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsRespuestaCove.ConsultarRespuestaCoveResponse> ConsultarRespuestaCoveAsync(wsRespuestaCove.SolicitarConsultarRespuestaCoveServicio solicitarConsultarRespuestaCoveServicio)
        {
            wsRespuestaCove.ConsultarRespuestaCoveRequest inValue = new wsRespuestaCove.ConsultarRespuestaCoveRequest();
            inValue.solicitarConsultarRespuestaCoveServicio = solicitarConsultarRespuestaCoveServicio;
            return ((wsRespuestaCove.IReceptor)(this)).ConsultarRespuestaCoveAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IReceptorBinding))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.TransportWithMessageCredential;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IReceptorBinding))
            {
                return new System.ServiceModel.EndpointAddress("https://www.ventanillaunica.gob.mx:8110/ventanilla/ConsultarRespuestaCoveService");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReceptorClient.GetBindingForEndpoint(EndpointConfiguration.IReceptorBinding);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReceptorClient.GetEndpointAddress(EndpointConfiguration.IReceptorBinding);
        }
        
        public enum EndpointConfiguration
        {
            
            IReceptorBinding,
        }
    }
}
